# Generated by Django 5.1.3 on 2025-01-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
