# Generated by Django 5.1.3 on 2025-01-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0002_alter_authuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='username',
        ),
    ]
